#!/usr/bin/env julia

import Pkg
Pkg.activate(".")

import Base: prompt
import MySQLClient

host = string(prompt("host"))
username = string(prompt("username"))
password = String(Base.getpass("password").data)
port = parse(Int, prompt("port"))
sock = MySQLClient.connect(host, username, password, port)

print("\n\n")
while true
    query = Base.prompt("mysql")
    if isnothing(query) || string(query) == "quit"
        print("Bye")
        exit(0)
    end
    MySQLClient.execute(sock, string(query))
    println()
end
